parameters:

services:

    retrive.tag.subscriber:
        class: Bundle\MainBundle\Subscriber\RetriveTagSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }